const { Client } = require('pg');
require('dotenv').config();

const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
});

const firstNames = ["Ana", "Bruno", "Carlos", "Daniel", "Eduardo", "Fernanda", "Gabriel", "Helena", "Igor", "Julia", "Lucas", "Mariana", "Nicolas", "Olivia", "Pedro", "Rafael", "Sara", "Thiago", "Vitoria", "Wagner", "Amanda", "Beatriz", "Caio", "Diego", "Elisa", "Felipe", "Gabriela", "Hugo", "Isabela", "Joao"];
const lastNames = ["Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Almeida", "Pereira", "Lima", "Gomes", "Costa", "Martins", "Barbosa", "Ribeiro", "Alves", "Cardoso", "Teixeira", "Correia", "Mendes", "Nunes"];

function generateName() {
    const first = firstNames[Math.floor(Math.random() * firstNames.length)];
    const last = lastNames[Math.floor(Math.random() * lastNames.length)];
    return `${first} ${last}`;
}

function generateEmail(name) {
    const parts = name.toLowerCase().split(' ');
    return `${parts[0]}.${parts[1]}@sesisenaisp.org.br`;
}

async function getMaxNif(prefix) {
    const res = await client.query("SELECT nif FROM users WHERE nif LIKE $1 ORDER BY nif DESC LIMIT 1", [prefix + '%']);
    if (res.rows.length === 0) return 0;
    const maxNif = res.rows[0].nif;
    const numPart = parseInt(maxNif.substring(2));
    return isNaN(numPart) ? 0 : numPart;
}

async function run() {
    await client.connect();
    try {
        console.log('Fetching max NIFs...');
        const maxSS = await getMaxNif('SS');
        const maxSN = await getMaxNif('SN');
        
        console.log(`Max SS: ${maxSS}, Max SN: ${maxSN}`);

        const countPerType = 60; // Total 120 users
        const password = '123456';
        const createdBy = 'ScriptAutoGenerated';

        // Insert SS users
        console.log(`Inserting ${countPerType} SS users starting from ${maxSS + 1}...`);
        for (let i = 1; i <= countPerType; i++) {
            const currentNum = maxSS + i;
            const nif = `SS${currentNum.toString().padStart(7, '0')}`;
            const name = generateName();
            const email = generateEmail(name);
            
            await client.query(
                "INSERT INTO users (nif, name, email, password, created_by, created_at, updated_at, is_active) VALUES ($1, $2, $3, $4, $5, NOW(), NOW(), true)",
                [nif, name, email, password, createdBy]
            );
        }

        // Insert SN users
        console.log(`Inserting ${countPerType} SN users starting from ${maxSN + 1}...`);
        for (let i = 1; i <= countPerType; i++) {
            const currentNum = maxSN + i;
            const nif = `SN${currentNum.toString().padStart(7, '0')}`;
            const name = generateName();
            const email = generateEmail(name);
            
            await client.query(
                "INSERT INTO users (nif, name, email, password, created_by, created_at, updated_at, is_active) VALUES ($1, $2, $3, $4, $5, NOW(), NOW(), true)",
                [nif, name, email, password, createdBy]
            );
        }
        
        console.log('Insertion complete.');

    } catch (err) {
        console.error('Error inserting users:', err);
    } finally {
        await client.end();
    }
}

run();
